name: quartier-depot-self-checkout
base: core22
version: "0.0.1"
summary: Self Checkout for Quartier-Depot
description: Self-checkout cash register for a self-service store using a WooCommerce backend.

grade: devel
confinement: devmode

apps:
  quartier-depot-self-checkout:
    command: bin/start-webserver.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
    options:
      woocommerce-url:
        type: string
        default: https://webshop.quartier-depot.ch/
        description: The WooCommerce root url
      woocommerce-consumer-key:
        type: string
        default: ck
        description: The WooCommerce consumer key
      woocommerce-consumer-secret:
        type: string
        default: cs
        description: The WooCommerce consumer secret
      appinsights-connection-string:
        type: string
        default: appInsights
        description: The AppInsights connection string
parts:
  node:
    plugin: npm
    source: .
    npm-node-version: 22.14.0
    npm-include-node: true

  dist:
    plugin: dump
    source: dist/
    organize:
      "*": dist/

  bin:
    plugin: dump
    source: bin
    organize:
      "start-webserver.sh": "bin/start-webserver.sh"
    override-build: |
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      install -m 755 $SNAPCRAFT_PROJECT_DIR/bin/start-webserver.sh $SNAPCRAFT_PART_INSTALL/bin/start-webserver.sh